org: tembusu
app: serverless-framework-test
service: serverless-framework-test
configValidationMode: error
useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: tembusu
  memorySize: 128
  timeout: 10
  logRetentionInDays: 14
  architecture: arm64

custom:
  urlDomain:
    apiDomain: ${env:SUBDOMAIN}.tembusu.link  # change by your custom domain
    hostedZoneName: tembusu.link.  # your domain Route 53 hosted zone name
    certificateArn: 'arn:aws:acm:us-east-1:355764785838:certificate/77bff5cb-03c7-4b11-ba8e-312e6f49a31f'
  wsgi:
    app: serverless.app
  prune:
    automatic: true
    number: 3



functions:
  api:
    handler: wsgi_handler.handler
    layers:
      - arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension-Arm64:2
    url: true
  cronJob:
    handler: async_tasks.hello_cron
    timeout: 300
    events:
      - schedule:
          name: cron-say-hello-${opt:stage, 'dev'}
          description: a description of my scheduled event's purpose
          # Can also be an array of rate/cron expressions
          rate: rate(20 minutes)
          # (default: true)
          enabled: true



plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-aws-function-url-custom-domain
