org: tembusu
app: serverless-framework-test
service: serverless-framework-test
configValidationMode: error

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  customDomain:
    http:
      domainName: hello.tembusu.link
      #stage: ci
      #basePath: api
      certificateName: '*.tembusu.link'
      createRoute53Record: true
      createRoute53IPv6Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2

provider:
  name: aws
  runtime: python3.9
  profile: tembusu
  memorySize: 128
  timeout: 30
  logRetentionInDays: 14
  architecture: arm64

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
  cronJob:
    handler: app.hello_cron
    events:
      - schedule:
          name: cron-say-hello
          description: a description of my scheduled event's purpose
          # Can also be an array of rate/cron expressions
          rate: rate(2 minutes)
          # (default: true)
          enabled: true



plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-domain-manager
